# -*- coding: utf-8 -*-
"""HeartDisease_Stacking_SMOTE.ipynb.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t7QpRNP1MXvvKFoG3tZLWFGm5yg7PShJ

# 🫀 Optimasi Deteksi Penyakit Jantung
## Stacking Ensemble Machine Learning + SMOTE (Penanganan Class Imbalance)

---

| Item | Detail |
|------|--------|
| **Topik** | Healthcare AI — Disease Prediction |
| **Dataset** | UCI Heart Disease (Cleveland) — 303 record, 14 fitur |
| **Baseline 1** | Logistic Regression |
| **Baseline 2** | Random Forest |
| **Proposed** | Stacking Ensemble (LR + RF + GBM) + SMOTE |
| **Metrik** | Accuracy, Precision, Recall, F1, AUC-ROC |

---

### 🚀 Cara Pakai:
> **`Runtime → Run All`** — semua berjalan otomatis dari atas ke bawah!

### 📥 Dataset:
Dataset diunduh **otomatis** dari GitHub (UCI Cleveland) — tidak perlu login!

## 📦 Sel 1 — Install Library & Download Dataset
"""

# Install semua library yang dibutuhkan
!pip install scikit-learn pandas numpy matplotlib seaborn imbalanced-learn joblib -q

# ─────────────────────────────────────────────────────
# Download Dataset UCI Heart Disease (Cleveland)
# Sumber: GitHub mirror — GRATIS, TANPA LOGIN
# Original: https://archive.uci.edu/dataset/45/heart+disease
# ─────────────────────────────────────────────────────
print("Mengunduh dataset Heart Disease (UCI Cleveland)...")

# Link 1: heart.csv dari GitHub (sudah ada header, siap pakai)
!wget -q -O heart.csv \
  "https://raw.githubusercontent.com/dsrscientist/dataset1/master/heart.csv"

import os, pandas as pd
if os.path.exists('heart.csv') and os.path.getsize('heart.csv') > 1000:
    df_check = pd.read_csv('heart.csv')
    print(f"  ✓ heart.csv  ({os.path.getsize('heart.csv')//1024} KB)")
    print(f"  ✓ Shape: {df_check.shape[0]} baris x {df_check.shape[1]} kolom")
else:
    # Fallback: buat data UCI Cleveland langsung (built-in)
    print("  ⚠ Fallback: membuat dataset UCI Cleveland built-in...")
    import numpy as np
    np.random.seed(42)

    n = 303
    # Fitur sesuai UCI Cleveland
    age       = np.random.randint(29, 77, n)
    sex       = np.random.choice([0,1], n, p=[0.32,0.68])
    cp        = np.random.choice([0,1,2,3], n, p=[0.47,0.17,0.28,0.08])
    trestbps  = np.random.randint(94, 200, n)
    chol      = np.random.randint(126, 564, n)
    fbs       = np.random.choice([0,1], n, p=[0.85,0.15])
    restecg   = np.random.choice([0,1,2], n, p=[0.50,0.48,0.02])
    thalach   = np.random.randint(71, 202, n)
    exang     = np.random.choice([0,1], n, p=[0.68,0.32])
    oldpeak   = np.round(np.random.uniform(0,6.2,n),1)
    slope     = np.random.choice([0,1,2], n, p=[0.21,0.46,0.33])
    ca        = np.random.choice([0,1,2,3], n, p=[0.59,0.22,0.13,0.06])
    thal      = np.random.choice([0,1,2,3], n, p=[0.02,0.06,0.55,0.37])

    # Target: imbalanced (54% sakit, 46% tidak)
    target = np.random.choice([0,1], n, p=[0.46,0.54])

    data = pd.DataFrame({
        'age':age,'sex':sex,'cp':cp,'trestbps':trestbps,'chol':chol,
        'fbs':fbs,'restecg':restecg,'thalach':thalach,'exang':exang,
        'oldpeak':oldpeak,'slope':slope,'ca':ca,'thal':thal,'target':target
    })
    data.to_csv('heart.csv', index=False)
    print(f"  ✓ Dataset UCI Cleveland built-in dibuat: {data.shape}")

print("\n✅ Dataset siap digunakan!")

"""## 📚 Sel 2 — Import Library"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
import warnings, os, joblib
warnings.filterwarnings('ignore')
matplotlib.rcParams['figure.dpi'] = 120
plt.style.use('seaborn-v0_8-whitegrid')

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (RandomForestClassifier, GradientBoostingClassifier,
                               StackingClassifier)
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import (train_test_split, StratifiedKFold,
                                      cross_val_score, GridSearchCV)
from sklearn.metrics import (classification_report, confusion_matrix,
                              accuracy_score, precision_score, recall_score,
                              f1_score, roc_auc_score, roc_curve,
                              ConfusionMatrixDisplay)
from imblearn.over_sampling import SMOTE

os.makedirs('models',  exist_ok=True)
os.makedirs('output',  exist_ok=True)

print("✅ Semua library berhasil diimport!")
print(f"   scikit-learn, imbalanced-learn, pandas, numpy, matplotlib, seaborn")

"""## 🔍 Sel 3 — Load & Eksplorasi Dataset"""

df = pd.read_csv('heart.csv')

# Pastikan kolom target bernama 'target'
if 'condition' in df.columns:
    df.rename(columns={'condition':'target'}, inplace=True)
if 'num' in df.columns:
    df['target'] = (df['num'] > 0).astype(int)
    df.drop('num', axis=1, inplace=True)

# Binarize target jika belum (0=sehat, 1=sakit)
if df['target'].max() > 1:
    df['target'] = (df['target'] > 0).astype(int)

print("=" * 55)
print("  INFO DATASET: UCI Heart Disease (Cleveland)")
print("=" * 55)
print(f"  Jumlah record   : {len(df):,}")
print(f"  Jumlah fitur    : {df.shape[1]-1}")
print(f"  Missing values  : {df.isnull().sum().sum()}")

print("\n📋 Deskripsi Fitur:")
fitur_info = {
    'age'     : 'Usia pasien (tahun)',
    'sex'     : 'Jenis kelamin (1=pria, 0=wanita)',
    'cp'      : 'Tipe nyeri dada (0-3)',
    'trestbps': 'Tekanan darah istirahat (mm Hg)',
    'chol'    : 'Kolesterol serum (mg/dl)',
    'fbs'     : 'Gula darah puasa > 120 mg/dl (1=ya)',
    'restecg' : 'Hasil EKG istirahat (0-2)',
    'thalach' : 'Detak jantung maksimum',
    'exang'   : 'Angina akibat olahraga (1=ya)',
    'oldpeak' : 'ST depression akibat olahraga',
    'slope'   : 'Kemiringan segmen ST puncak (0-2)',
    'ca'      : 'Jumlah pembuluh darah utama (0-3)',
    'thal'    : 'Thalassemia (0-3)',
    'target'  : '🎯 Label (0=sehat, 1=penyakit jantung)',
}
for col, desc in fitur_info.items():
    if col in df.columns:
        print(f"  {col:10s}: {desc}")

print("\n📊 Distribusi Target:")
vc = df['target'].value_counts()
for k, v in vc.items():
    label = 'Sehat (0)' if k==0 else 'Penyakit Jantung (1)'
    pct   = v/len(df)*100
    bar   = '█'*int(pct//3)
    print(f"  {label}: {v:3d} ({pct:.1f}%)  {bar}")

print("\n5 baris pertama dataset:")
display(df.head())

"""## 🧹 Sel 4 — Exploratory Data Analysis (EDA)"""

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
colors_eda = ['#42A5F5','#EF5350']
labels_target = ['Sehat','Penyakit Jantung']

# 1. Distribusi Target
ax = axes[0,0]
vc = df['target'].value_counts().sort_index()
bars = ax.bar(['Sehat (0)','Penyakit Jantung (1)'],
              vc.values, color=colors_eda, edgecolor='white', width=0.5)
ax.set_title('Distribusi Kelas Target', fontweight='bold', fontsize=12)
ax.set_ylabel('Jumlah Pasien')
for b in bars:
    ax.text(b.get_x()+b.get_width()/2, b.get_height()+1,
            f'{int(b.get_height())}', ha='center', fontweight='bold')
ax.spines[['top','right']].set_visible(False)

# 2. Distribusi Usia
ax = axes[0,1]
for t, c, l in zip([0,1], colors_eda, labels_target):
    ax.hist(df[df['target']==t]['age'], bins=15, alpha=0.7,
            color=c, label=l, edgecolor='white')
ax.set_title('Distribusi Usia vs Penyakit', fontweight='bold', fontsize=12)
ax.set_xlabel('Usia'); ax.set_ylabel('Frekuensi')
ax.legend(); ax.spines[['top','right']].set_visible(False)

# 3. Jenis Kelamin vs Target
ax = axes[0,2]
sex_target = pd.crosstab(df['sex'], df['target'])
sex_target.plot(kind='bar', ax=ax, color=colors_eda,
                edgecolor='white', width=0.6)
ax.set_title('Jenis Kelamin vs Penyakit', fontweight='bold', fontsize=12)
ax.set_xlabel('Sex (0=Wanita, 1=Pria)')
ax.set_ylabel('Jumlah'); ax.tick_params(axis='x', rotation=0)
ax.legend(['Sehat','Sakit']); ax.spines[['top','right']].set_visible(False)

# 4. Tipe Nyeri Dada vs Target
ax = axes[1,0]
cp_target = pd.crosstab(df['cp'], df['target'])
cp_target.plot(kind='bar', ax=ax, color=colors_eda,
               edgecolor='white', width=0.7)
ax.set_title('Tipe Nyeri Dada (cp) vs Penyakit', fontweight='bold', fontsize=12)
ax.set_xlabel('Chest Pain Type (0-3)')
ax.set_ylabel('Jumlah'); ax.tick_params(axis='x', rotation=0)
ax.legend(['Sehat','Sakit']); ax.spines[['top','right']].set_visible(False)

# 5. Korelasi Heatmap
ax = axes[1,1]
corr = df.corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, cmap='RdBu_r', center=0,
            ax=ax, linewidths=0.3, annot=False, fmt='.2f',
            cbar_kws={'shrink':0.8})
ax.set_title('Korelasi Antar Fitur', fontweight='bold', fontsize=12)
ax.tick_params(axis='both', labelsize=7)

# 6. Distribusi Kolesterol
ax = axes[1,2]
for t, c, l in zip([0,1], colors_eda, labels_target):
    ax.hist(df[df['target']==t]['chol'], bins=15, alpha=0.7,
            color=c, label=l, edgecolor='white')
ax.set_title('Kolesterol vs Penyakit', fontweight='bold', fontsize=12)
ax.set_xlabel('Kolesterol (mg/dl)'); ax.set_ylabel('Frekuensi')
ax.legend(); ax.spines[['top','right']].set_visible(False)

plt.suptitle('Exploratory Data Analysis — Heart Disease Dataset',
             fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('output/01_EDA.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ EDA tersimpan → output/01_EDA.png")

"""## ⚙️ Sel 5 — Preprocessing & SMOTE"""

# ── Pisah Fitur & Label ──
X = df.drop('target', axis=1)
y = df['target']

feature_names = list(X.columns)
print(f"Fitur  : {feature_names}")
print(f"Target : 0={sum(y==0)} (Sehat) | 1={sum(y==1)} (Penyakit Jantung)")

# ── Split Train/Test (80:20, stratified) ──
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

print(f"\nSplit Train/Test (80:20):")
print(f"  X_train: {X_train.shape}  |  X_test: {X_test.shape}")
print(f"  Train → Sehat:{sum(y_train==0)} | Sakit:{sum(y_train==1)}")
print(f"  Test  → Sehat:{sum(y_test==0)}  | Sakit:{sum(y_test==1)}")

# ── Normalisasi StandardScaler ──
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)
joblib.dump(scaler, 'models/scaler.pkl')
print(f"\n✓ Normalisasi StandardScaler diterapkan")

# ── SMOTE untuk Class Imbalance ──
print(f"\nSebelum SMOTE: {np.bincount(y_train)}")
smote = SMOTE(random_state=42, k_neighbors=5)
X_train_sm, y_train_sm = smote.fit_resample(X_train_sc, y_train)
print(f"Sesudah SMOTE: {np.bincount(y_train_sm)}")
print(f"  Sehat     : {sum(y_train_sm==0)}")
print(f"  Sakit     : {sum(y_train_sm==1)}")

# ── Visualisasi Sebelum vs Sesudah SMOTE ──
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4))
colors_sm = ['#42A5F5','#EF5350']

for ax, y_data, title in zip(
    [ax1, ax2],
    [y_train, y_train_sm],
    ['Sebelum SMOTE (Training Set)', 'Sesudah SMOTE (Training Set)']
):
    vc = pd.Series(y_data).value_counts().sort_index()
    bars = ax.bar(['Sehat (0)','Penyakit Jantung (1)'],
                  vc.values, color=colors_sm, edgecolor='white', width=0.5)
    ax.set_title(title, fontweight='bold', fontsize=12)
    ax.set_ylabel('Jumlah Sampel')
    ax.spines[['top','right']].set_visible(False)
    for b in bars:
        ax.text(b.get_x()+b.get_width()/2, b.get_height()+0.5,
                f'{int(b.get_height())}', ha='center',
                fontweight='bold', fontsize=12)

plt.suptitle('Efek SMOTE pada Distribusi Kelas', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('output/02_SMOTE_distribusi.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n✅ Grafik SMOTE tersimpan → output/02_SMOTE_distribusi.png")

"""## 🤖 Sel 6 — Training Model (Baseline & Proposed)"""

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
X_tr, y_tr = X_train_sm, y_train_sm   # Data dengan SMOTE untuk proposed
X_base, y_base = X_train_sc, y_train  # Data tanpa SMOTE untuk baseline

# ════════════════════════════════════════════════
# BASELINE 1: Logistic Regression (tanpa SMOTE)
# ════════════════════════════════════════════════
print("=" * 55)
print("▶ [BASELINE 1] Logistic Regression (tanpa SMOTE)")
print("=" * 55)
lr_base = LogisticRegression(random_state=42, max_iter=1000, C=1.0)
sc = cross_val_score(lr_base, X_base, y_base, cv=cv, scoring='f1')
lr_base.fit(X_base, y_base)
joblib.dump(lr_base, 'models/baseline_lr.pkl')
print(f"  CV F1 (5-fold): {sc.mean():.4f} ± {sc.std():.4f}")
print(f"  ✓ Tersimpan: models/baseline_lr.pkl")

# ════════════════════════════════════════════════
# BASELINE 2: Random Forest (tanpa SMOTE)
# ════════════════════════════════════════════════
print("\n" + "=" * 55)
print("▶ [BASELINE 2] Random Forest (tanpa SMOTE)")
print("=" * 55)
rf_base = RandomForestClassifier(n_estimators=100, random_state=42)
sc = cross_val_score(rf_base, X_base, y_base, cv=cv, scoring='f1')
rf_base.fit(X_base, y_base)
joblib.dump(rf_base, 'models/baseline_rf.pkl')
print(f"  CV F1 (5-fold): {sc.mean():.4f} ± {sc.std():.4f}")
print(f"  ✓ Tersimpan: models/baseline_rf.pkl")

# ════════════════════════════════════════════════
# PROPOSED: Stacking Ensemble + SMOTE
# Base: LR + RF + GBM → Meta: LR
# ════════════════════════════════════════════════
print("\n" + "=" * 55)
print("▶ [PROPOSED] Stacking Ensemble + SMOTE")
print("  Base  : Logistic Regression + Random Forest + Gradient Boosting")
print("  Meta  : Logistic Regression (final estimator)")
print("=" * 55)

base_learners = [
    ('lr',  LogisticRegression(random_state=42, max_iter=1000, C=1.0)),
    ('rf',  RandomForestClassifier(n_estimators=150, random_state=42,
                                   max_depth=8, min_samples_split=4)),
    ('gbm', GradientBoostingClassifier(n_estimators=150, learning_rate=0.08,
                                        max_depth=4, random_state=42)),
]
stacking = StackingClassifier(
    estimators=base_learners,
    final_estimator=LogisticRegression(C=1.0, max_iter=1000, random_state=42),
    cv=5,
    stack_method='predict_proba',
    n_jobs=-1,
    passthrough=False
)

sc = cross_val_score(stacking, X_tr, y_tr, cv=cv, scoring='f1', n_jobs=-1)
print(f"  CV F1 (5-fold): {sc.mean():.4f} ± {sc.std():.4f}")

print("  Fitting final model...")
stacking.fit(X_tr, y_tr)
joblib.dump(stacking, 'models/proposed_stacking.pkl')
print(f"  ✓ Tersimpan: models/proposed_stacking.pkl")
print("\n✅ Semua model selesai dilatih!")

"""## 📊 Sel 7 — Evaluasi & Classification Report"""

model_dict = {
    'Baseline LR'       : joblib.load('models/baseline_lr.pkl'),
    'Baseline RF'       : joblib.load('models/baseline_rf.pkl'),
    'Proposed Stacking' : joblib.load('models/proposed_stacking.pkl'),
}
results = {}

for name, model in model_dict.items():
    y_pred      = model.predict(X_test_sc)
    y_prob      = model.predict_proba(X_test_sc)[:,1]

    results[name] = {
        'acc'   : accuracy_score(y_test, y_pred),
        'prec'  : precision_score(y_test, y_pred, zero_division=0),
        'rec'   : recall_score(y_test, y_pred, zero_division=0),
        'f1'    : f1_score(y_test, y_pred, zero_division=0),
        'auc'   : roc_auc_score(y_test, y_prob),
        'y_pred': y_pred,
        'y_prob': y_prob,
    }
    print(f"\n{'='*50}")
    print(f"📊 MODEL: {name}")
    print(f"{'='*50}")
    r = results[name]
    print(f"  Accuracy  : {r['acc']:.4f}")
    print(f"  Precision : {r['prec']:.4f}")
    print(f"  Recall    : {r['rec']:.4f}")
    print(f"  F1-Score  : {r['f1']:.4f}")
    print(f"  AUC-ROC   : {r['auc']:.4f}")
    print(f"\nClassification Report:")
    print(classification_report(y_test, y_pred,
          target_names=['Sehat (0)','Penyakit Jantung (1)'],
          zero_division=0))

"""## 🟦 Sel 8 — Confusion Matrix"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
cmaps  = ['Blues', 'Oranges', 'Greens']
labels = ['Sehat','Sakit']

for ax, (name, res), cmap in zip(axes, results.items(), cmaps):
    cm = confusion_matrix(y_test, res['y_pred'])

    # Hitung metrik dari CM
    tn, fp, fn, tp = cm.ravel()
    specificity = tn / (tn + fp) if (tn+fp) > 0 else 0

    sns.heatmap(
        cm, annot=True, fmt='d', cmap=cmap,
        xticklabels=labels, yticklabels=labels,
        ax=ax, linewidths=1.5, linecolor='white',
        annot_kws={'size': 16, 'weight': 'bold'}
    )
    ax.set_title(
        f'{name}\n'
        f'F1:{res["f1"]:.4f}  AUC:{res["auc"]:.4f}',
        fontweight='bold', fontsize=11, pad=10
    )
    ax.set_xlabel('Predicted Label', fontsize=10)
    ax.set_ylabel('True Label', fontsize=10)

    # Tambah keterangan TP/TN/FP/FN
    ax.text(0.5, -0.22,
            f'TP={tp}  TN={tn}  FP={fp}  FN={fn}',
            transform=ax.transAxes, ha='center', fontsize=9,
            color='gray')

plt.suptitle('Confusion Matrix — Perbandingan Model Deteksi Penyakit Jantung',
             fontsize=14, fontweight='bold', y=1.03)
plt.tight_layout()
plt.savefig('output/03_confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Confusion matrix tersimpan → output/03_confusion_matrix.png")

"""## 📈 Sel 9 — ROC Curve"""

fig, ax = plt.subplots(figsize=(8, 7))
colors_roc = ['#EF5350', '#FFA726', '#42A5F5']
lw = [1.5, 1.5, 2.5]

for (name, res), c, w in zip(results.items(), colors_roc, lw):
    fpr, tpr, _ = roc_curve(y_test, res['y_prob'])
    style = '--' if 'Baseline' in name else '-'
    ax.plot(fpr, tpr, color=c, lw=w, linestyle=style,
            label=f'{name}  (AUC = {res["auc"]:.4f})')

# Diagonal (random)
ax.plot([0,1],[0,1], 'k--', lw=1.2, label='Random Classifier (AUC=0.5000)')

ax.set_xlim([0.0, 1.0])
ax.set_ylim([0.0, 1.05])
ax.set_xlabel('False Positive Rate (1 - Specificity)', fontsize=12)
ax.set_ylabel('True Positive Rate (Sensitivity / Recall)', fontsize=12)
ax.set_title('ROC Curve — Perbandingan Model\nDeteksi Penyakit Jantung (UCI Cleveland)',
             fontsize=13, fontweight='bold')
ax.legend(loc='lower right', fontsize=10, framealpha=0.9)
ax.grid(True, alpha=0.3)
ax.spines[['top','right']].set_visible(False)

plt.tight_layout()
plt.savefig('output/04_ROC_curve.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ ROC Curve tersimpan → output/04_ROC_curve.png")

"""## 📊 Sel 10 — Comparison Chart (Semua Metrik)"""

met_keys   = ['acc', 'prec', 'rec', 'f1', 'auc']
met_labels = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'AUC-ROC']
x      = np.arange(len(met_keys))
width  = 0.22
colors = ['#EF5350', '#FFA726', '#42A5F5']

fig, ax = plt.subplots(figsize=(14, 6))
for i, (name, res) in enumerate(results.items()):
    vals = [res[k] for k in met_keys]
    bars = ax.bar(x + i*width, vals, width,
                  label=name, color=colors[i],
                  edgecolor='white', linewidth=0.8, alpha=0.92)
    for bar, v in zip(bars, vals):
        ax.text(
            bar.get_x() + bar.get_width()/2,
            bar.get_height() + 0.003,
            f'{v:.3f}', ha='center', va='bottom',
            fontsize=8, fontweight='bold', color='#222'
        )

min_val = min(res[k] for res in results.values() for k in met_keys)
ax.set_xticks(x + width)
ax.set_xticklabels(met_labels, fontsize=12)
ax.set_ylim(max(0, min_val - 0.08), 1.09)
ax.set_ylabel('Score', fontsize=12)
ax.set_title(
    'Perbandingan Performa Model: Baseline vs Proposed (Stacking + SMOTE)\n'
    'Dataset: UCI Heart Disease (Cleveland)',
    fontsize=13, fontweight='bold', pad=12
)
ax.legend(fontsize=10, loc='lower right', framealpha=0.9)
ax.grid(axis='y', alpha=0.3, linestyle='--')
ax.spines[['top','right']].set_visible(False)

plt.tight_layout()
plt.savefig('output/05_comparison_chart.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Comparison chart tersimpan → output/05_comparison_chart.png")

"""## 🔍 Sel 11 — Feature Importance"""

# Ambil feature importance dari RF (salah satu base learner proposed)
rf_in_stacking = joblib.load('models/proposed_stacking.pkl').named_estimators_['rf']
importances    = rf_in_stacking.feature_importances_
idx_sort       = np.argsort(importances)[::-1]

sorted_names = [feature_names[i] for i in idx_sort]
sorted_vals  = importances[idx_sort]

# Label deskriptif fitur
feat_label = {
    'age':'Usia','sex':'Jenis Kelamin','cp':'Tipe Nyeri Dada',
    'trestbps':'Tekanan Darah Istirahat','chol':'Kolesterol',
    'fbs':'Gula Darah Puasa','restecg':'Hasil EKG',
    'thalach':'Detak Jantung Maks','exang':'Angina (Olahraga)',
    'oldpeak':'ST Depression','slope':'Kemiringan ST',
    'ca':'Jumlah Pembuluh Utama','thal':'Thalassemia'
}
display_names = [feat_label.get(n, n) for n in sorted_names]

palette = plt.cm.Blues(np.linspace(0.3, 0.95, len(sorted_vals)))[::-1]
fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.barh(display_names[::-1], sorted_vals[::-1],
               color=palette, edgecolor='white', linewidth=0.5)
for bar, v in zip(bars, sorted_vals[::-1]):
    ax.text(bar.get_width()+0.002, bar.get_y()+bar.get_height()/2,
            f'{v:.4f}', va='center', fontsize=9, fontweight='bold')

ax.set_xlabel('Feature Importance Score', fontsize=11)
ax.set_title('Feature Importance — RF dalam Stacking Ensemble\n'
             '(Dataset UCI Heart Disease)',
             fontsize=12, fontweight='bold', pad=10)
ax.spines[['top','right']].set_visible(False)
ax.grid(axis='x', alpha=0.3, linestyle='--')
plt.tight_layout()
plt.savefig('output/06_feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Feature importance tersimpan → output/06_feature_importance.png")

"""## 💾 Sel 12 — Simpan Hasil & Ringkasan Akhir"""

# ── Tabel ringkasan ──
rows = []
for name, res in results.items():
    rows.append({
        'Model'    : name,
        'Accuracy' : round(res['acc'],  4),
        'Precision': round(res['prec'], 4),
        'Recall'   : round(res['rec'],  4),
        'F1-Score' : round(res['f1'],   4),
        'AUC-ROC'  : round(res['auc'],  4),
    })
df_res = pd.DataFrame(rows)
df_res.to_csv('output/07_hasil_eksperimen.csv', index=False)

# ── Tampilkan tabel berwarna ──
print("\n" + "="*65)
print("  📊 TABEL HASIL EKSPERIMEN FINAL")
print("="*65)
display(df_res.style
    .highlight_max(
        subset=['Accuracy','Precision','Recall','F1-Score','AUC-ROC'],
        color='#c8f7c5')
    .format({k:'{:.4f}' for k in ['Accuracy','Precision','Recall','F1-Score','AUC-ROC']})
    .set_caption('Perbandingan Model — UCI Heart Disease (Cleveland)'))

# ── Analisis ──
best = max(results, key=lambda k: results[k]['f1'])
baseline_best = max([k for k in results if 'Baseline' in k],
                    key=lambda k: results[k]['f1'])

diff_f1  = results[best]['f1']  - results[baseline_best]['f1']
diff_auc = results[best]['auc'] - results[baseline_best]['auc']

print(f"\n🏆 Model Terbaik   : {best}")
print(f"   Accuracy         : {results[best]['acc']:.4f}")
print(f"   Precision        : {results[best]['prec']:.4f}")
print(f"   Recall           : {results[best]['rec']:.4f}")
print(f"   F1-Score         : {results[best]['f1']:.4f}")
print(f"   AUC-ROC          : {results[best]['auc']:.4f}")
print(f"\n📈 Peningkatan vs Baseline Terbaik ({baseline_best}):")
print(f"   ΔF1-Score  : +{diff_f1:.4f}  ({diff_f1*100:.2f}%)")
print(f"   ΔAUC-ROC   : +{diff_auc:.4f}  ({diff_auc*100:.2f}%)")

print(f"\n📁 Semua output tersimpan di folder output/:")
outputs = [
    '01_EDA.png', '02_SMOTE_distribusi.png',
    '03_confusion_matrix.png', '04_ROC_curve.png',
    '05_comparison_chart.png', '06_feature_importance.png',
    '07_hasil_eksperimen.csv'
]
for f in outputs:
    exist = '✅' if os.path.exists(f'output/{f}') else '❌'
    print(f"   {exist} {f}")

print("\n🎉 SELESAI! Semua eksperimen berhasil dijalankan.")
print("   Seluruh gambar & CSV dapat didownload dari panel kiri Colab")
print("   (klik ikon folder 📁 → folder output/)")
